import type { ActivityItem, KpiItem, StatusTone } from "./types";

export const executiveHeader = {
  projectName: "Plataforma Universitaria Integral",
  status: "En progreso",
  version: "MVP Fase 1",
  updatedAt: "17 May 2026 · 09:42 UTC-6",
  environment: "Production",
  leader: "Mtra. Daniela Ortega",
  leaderRole: "Project Lead",
  online: true,
};

export const kpis: KpiItem[] = [
  { label: "Avance global", value: "74%", trend: "+6.2%", tone: "success", icon: "Gauge", micro: "12 tareas cerradas esta semana" },
  { label: "Tareas completadas", value: "186", trend: "+19", tone: "success", icon: "CheckCircle2", micro: "Sprint 3 en fase de QA" },
  { label: "Tareas pendientes", value: "64", trend: "-8", tone: "info", icon: "ListTodo", micro: "51 en ejecución, 13 sin iniciar" },
  { label: "Bloqueos activos", value: "5", trend: "-2", tone: "warning", icon: "ShieldAlert", micro: "2 críticos, 3 medios" },
  { label: "Squads trabajando", value: "4", trend: "0", tone: "info", icon: "Users", micro: "24 integrantes totales" },
  { label: "Uptime sistema", value: "99.93%", trend: "+0.08%", tone: "success", icon: "Activity", micro: "Sin incidentes P1" },
  { label: "Commits semana", value: "97", trend: "+15", tone: "info", icon: "GitCommitHorizontal", micro: "35% backend, 65% frontend" },
  { label: "PRs aprobados", value: "28", trend: "+4", tone: "success", icon: "GitPullRequestArrow", micro: "Tiempo medio de revisión 7.6h" },
  { label: "Módulos terminados", value: "3/7", trend: "+1", tone: "info", icon: "PackageCheck", micro: "Autenticación, Dashboard, Notificaciones" },
];

export const roadmap = [
  {
    title: "Cierre de pruebas E2E en flujo de justificaciones",
    priority: "Alta",
    owner: "Squad 1 · Justificaciones",
    eta: "21 May 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Datos de control escolar en staging",
  },
  {
    title: "Integración final de recordatorios en motor de citas",
    priority: "Alta",
    owner: "Squad 3 · Citas",
    eta: "22 May 2026",
    sprint: "Sprint 3",
    status: "blocked" as StatusTone,
    dependency: "Webhook institucional de correo",
  },
  {
    title: "Hardening de auditoría y logging unificado",
    priority: "Media",
    owner: "Squad 2 · Auditoría",
    eta: "24 May 2026",
    sprint: "Sprint 3",
    status: "in-progress" as StatusTone,
    dependency: "Policy final de retención",
  },
  {
    title: "Plan de despliegue y validación go-live",
    priority: "Crítica",
    owner: "PMO + Arquitectura",
    eta: "27 May 2026",
    sprint: "Sprint 4",
    status: "delayed" as StatusTone,
    dependency: "Acta de aprobación directiva",
  },
];

export const sprints = [
  {
    name: "Sprint 0 — Infraestructura",
    progress: 100,
    total: 42,
    done: 42,
    owners: "Platform Team",
    risks: "Riesgo bajo",
    status: "completed" as StatusTone,
    deadline: "01 Apr 2026",
    dependencies: "Sin dependencias",
  },
  {
    name: "Sprint 1 — Autenticación",
    progress: 100,
    total: 58,
    done: 58,
    owners: "Squad 0 + Squad 4",
    risks: "Riesgo bajo",
    status: "completed" as StatusTone,
    deadline: "18 Apr 2026",
    dependencies: "OIDC institucional",
  },
  {
    name: "Sprint 2 — Citas y Notificaciones",
    progress: 83,
    total: 74,
    done: 61,
    owners: "Squad 3 + Squad 4",
    risks: "Riesgo medio",
    status: "in-progress" as StatusTone,
    deadline: "10 May 2026",
    dependencies: "API de agenda académica",
  },
  {
    name: "Sprint 3 — Justificaciones y QA",
    progress: 64,
    total: 76,
    done: 49,
    owners: "Squad 1 + QA Guild",
    risks: "Riesgo alto",
    status: "blocked" as StatusTone,
    deadline: "29 May 2026",
    dependencies: "Validación legal y escolar",
  },
];

export const modules = [
  {
    name: "Autenticación",
    description: "Control de acceso seguro para alumnos, docentes y administrativos con SSO universitario.",
    objective: "Habilitar ingreso unificado y trazable.",
    impact: "Reduce tiempos de soporte y aumenta seguridad de identidad.",
    mvpPriority: "Crítica",
    progress: 100,
    tasksDone: 29,
    tasksPending: 0,
    commits: 53,
    prsOpen: 0,
    bugs: 1,
    risk: "Bajo",
    techLead: "Ing. Karla Vega",
    squad: "Squad 4 - Notificaciones",
    assignees: ["Karla Vega", "Diego Salas", "Andrea Luna"],
    nextSteps: ["Monitoreo de sesiones", "Optimizar fallback MFA"],
    deliverables: ["Reporte de seguridad", "Política de expiración"],
    improvements: ["Auditoría de intentos fallidos"],
    dependencies: ["Proveedor OIDC"],
    blockers: ["Ninguno"],
    history: [
      { by: "Diego Salas", date: "14 May", type: "Hotfix", approval: "Aprobado", detail: "Parche de refresco de token en Safari." },
      { by: "Karla Vega", date: "11 May", type: "Feature", approval: "Aprobado", detail: "Alta de política de expiración adaptable por rol." },
    ],
  },
  {
    name: "Dashboard Base",
    description: "Vista central para jefaturas con métricas operativas y estratégicas del sistema.",
    objective: "Concentrar información ejecutiva en una sola pantalla.",
    impact: "Acelera toma de decisiones de coordinación académica.",
    mvpPriority: "Alta",
    progress: 88,
    tasksDone: 34,
    tasksPending: 5,
    commits: 41,
    prsOpen: 2,
    bugs: 2,
    risk: "Medio",
    techLead: "Mtra. Daniela Ortega",
    squad: "PMO + Squad 2",
    assignees: ["Daniela Ortega", "Jorge Prieto", "Maria Cota"],
    nextSteps: ["Conectar alertas en tiempo real", "Exportar KPI a PDF"],
    deliverables: ["Panel ejecutivo final", "Plantilla mensual de reporte"],
    improvements: ["Reorganizar jerarquía de KPIs"],
    dependencies: ["SDK analytics"],
    blockers: ["Definir prioridad de indicadores con dirección"],
    history: [
      { by: "Jorge Prieto", date: "15 May", type: "UI", approval: "En revisión", detail: "Ajuste de tarjetas KPI con contraste AA." },
      { by: "Daniela Ortega", date: "13 May", type: "Refactor", approval: "Aprobado", detail: "Nuevo motor de agregación de métricas." },
    ],
  },
  {
    name: "Notificaciones",
    description: "Orquestación de avisos por correo, push y bandeja interna para eventos académicos críticos.",
    objective: "Asegurar comunicación oportuna y verificable.",
    impact: "Reduce ausencias y retrasos administrativos.",
    mvpPriority: "Alta",
    progress: 92,
    tasksDone: 26,
    tasksPending: 3,
    commits: 39,
    prsOpen: 1,
    bugs: 2,
    risk: "Medio",
    techLead: "Lic. Hector Ibarra",
    squad: "Squad 4 - Notificaciones",
    assignees: ["Hector Ibarra", "Paulina Mora", "Gael Rosales"],
    nextSteps: ["Canal SMS de respaldo", "Plantillas por programa"],
    deliverables: ["Matriz de triggers", "Reporte de entrega por canal"],
    improvements: ["Retry policy por severidad"],
    dependencies: ["Proveedor SMTP institucional"],
    blockers: ["Límite de envíos por hora"],
    history: [
      { by: "Paulina Mora", date: "16 May", type: "Feature", approval: "Aprobado", detail: "Nueva cola de prioridad para avisos críticos." },
      { by: "Gael Rosales", date: "12 May", type: "Test", approval: "Aprobado", detail: "Suite de carga con 10k eventos." },
    ],
  },
  {
    name: "Citas",
    description: "Gestión integral de citas entre alumnos, docentes y personal de servicios escolares.",
    objective: "Ordenar disponibilidad y reducir fricción en agenda.",
    impact: "Incrementa ocupación de slots y puntualidad.",
    mvpPriority: "Crítica",
    progress: 79,
    tasksDone: 31,
    tasksPending: 8,
    commits: 47,
    prsOpen: 4,
    bugs: 4,
    risk: "Alto",
    techLead: "Ing. Raul Molina",
    squad: "Squad 3 - Citas",
    assignees: ["Raul Molina", "Ximena Trujillo", "Sofia Palafox"],
    nextSteps: ["Resolver colisiones de agenda", "Consolidar cancelaciones"],
    deliverables: ["Motor de disponibilidad v2", "Reporte de no-show"],
    improvements: ["Caching de calendario", "Normalizar husos horarios"],
    dependencies: ["API institucional de horarios"],
    blockers: ["Sincronización intermitente con LDAP"],
    history: [
      { by: "Raul Molina", date: "16 May", type: "Bugfix", approval: "Aprobado", detail: "Corregida condición de carrera en reservas simultáneas." },
      { by: "Ximena Trujillo", date: "10 May", type: "Feature", approval: "En revisión", detail: "Panel de reasignación masiva de citas." },
    ],
  },
  {
    name: "Justificaciones",
    description: "Flujo digital de justificación académica con evidencia y trazabilidad normativa.",
    objective: "Digitalizar proceso con auditoría completa.",
    impact: "Disminuye tiempos de resolución y errores manuales.",
    mvpPriority: "Crítica",
    progress: 68,
    tasksDone: 27,
    tasksPending: 13,
    commits: 44,
    prsOpen: 5,
    bugs: 6,
    risk: "Alto",
    techLead: "Mtra. Alejandra Rios",
    squad: "Squad 1 - Justificaciones",
    assignees: ["Alejandra Rios", "Iker Zamora", "Valeria Soto"],
    nextSteps: ["Firma digital en aprobaciones", "Validación de evidencias"],
    deliverables: ["Workflow de revisión", "Dashboard de casos abiertos"],
    improvements: ["Optimizar OCR de evidencias"],
    dependencies: ["Catálogo de reglamento escolar"],
    blockers: ["Pendiente homologación jurídica"],
    history: [
      { by: "Valeria Soto", date: "17 May", type: "Feature", approval: "En revisión", detail: "Carga múltiple de evidencias en lote." },
      { by: "Iker Zamora", date: "14 May", type: "Test", approval: "Aprobado", detail: "Pruebas de estrés de aprobación concurrente." },
    ],
  },
  {
    name: "Incidencias",
    description: "Registro y seguimiento de incidencias técnicas y operativas con priorización inteligente.",
    objective: "Reducir MTTR y evitar reincidencias.",
    impact: "Mejora continuidad operativa del campus.",
    mvpPriority: "Media",
    progress: 52,
    tasksDone: 19,
    tasksPending: 17,
    commits: 28,
    prsOpen: 3,
    bugs: 7,
    risk: "Medio",
    techLead: "Ing. Mateo Ceniceros",
    squad: "Squad 2 - Auditoria",
    assignees: ["Mateo Ceniceros", "Miriam Quintero", "Leo Cardenas"],
    nextSteps: ["SLAs por categoría", "Reglas automáticas de escalamiento"],
    deliverables: ["Matriz de severidad", "Vista de guardia"],
    improvements: ["Integrar runbooks"],
    dependencies: ["Servicio de monitoreo"],
    blockers: ["Sin acceso completo a logs históricos"],
    history: [
      { by: "Miriam Quintero", date: "15 May", type: "Ops", approval: "Aprobado", detail: "Clasificador inicial de severidad por impacto." },
      { by: "Leo Cardenas", date: "09 May", type: "Refactor", approval: "Aprobado", detail: "Nueva taxonomía de incidencias." },
    ],
  },
  {
    name: "Chatbot",
    description: "Asistente conversacional para consultas frecuentes de trámites y seguimiento académico.",
    objective: "Disminuir carga operativa de soporte.",
    impact: "Eleva velocidad de respuesta a estudiantes.",
    mvpPriority: "Media",
    progress: 45,
    tasksDone: 16,
    tasksPending: 20,
    commits: 22,
    prsOpen: 4,
    bugs: 5,
    risk: "Medio",
    techLead: "Lic. Fernanda Almaraz",
    squad: "Squad 2 - Auditoria",
    assignees: ["Fernanda Almaraz", "Nestor Cantu", "Iris Galindo"],
    nextSteps: ["Fine-tuning FAQ", "Métricas de satisfacción"],
    deliverables: ["Entrenamiento dominio escolar", "Panel de conversaciones"],
    improvements: ["RAG sobre reglamentos"],
    dependencies: ["Base de conocimiento académica"],
    blockers: ["Dataset etiquetado incompleto"],
    history: [
      { by: "Nestor Cantu", date: "16 May", type: "ML", approval: "En revisión", detail: "Nuevo prompt chain para intenciones ambiguas." },
      { by: "Fernanda Almaraz", date: "11 May", type: "Feature", approval: "Aprobado", detail: "Escalamiento a agente humano en baja confianza." },
    ],
  },
] as const;

export const globalActivity: ActivityItem[] = [
  { user: "Karla Vega", action: "merge", description: "Se fusiono rama feature/sso-role-lock para endurecer permisos.", module: "Autenticación", squad: "Squad 4", sprint: "Sprint 3", date: "17 May", time: "08:12", status: "Aprobado", impact: "Alto" },
  { user: "Raul Molina", action: "deploy", description: "Despliegue parcial de motor de disponibilidad con feature flag.", module: "Citas", squad: "Squad 3", sprint: "Sprint 3", date: "17 May", time: "07:30", status: "Exitoso", impact: "Medio" },
  { user: "Alejandra Rios", action: "validation", description: "Validacion de flujo de aprobacion de justificaciones con QA.", module: "Justificaciones", squad: "Squad 1", sprint: "Sprint 3", date: "16 May", time: "18:40", status: "Con observaciones", impact: "Alto" },
  { user: "Mateo Ceniceros", action: "hotfix", description: "Correccion de timeout en pipeline de auditoria de incidencias.", module: "Incidencias", squad: "Squad 2", sprint: "Sprint 2", date: "16 May", time: "14:05", status: "Aprobado", impact: "Medio" },
  { user: "Paulina Mora", action: "test", description: "Pruebas de carga del broker de notificaciones en 3 canales.", module: "Notificaciones", squad: "Squad 4", sprint: "Sprint 2", date: "15 May", time: "20:26", status: "Exitoso", impact: "Medio" },
  { user: "Daniela Ortega", action: "approval", description: "Aprobacion ejecutiva del tablero de KPI para direccion.", module: "Dashboard Base", squad: "PMO", sprint: "Sprint 3", date: "15 May", time: "11:12", status: "Aprobado", impact: "Alto" },
];

export const owners = [
  { name: "Daniela Ortega", squad: "PMO", role: "Project Lead", tasks: 14, progress: 84, weekly: "12 hitos", prs: 5, status: "activo" },
  { name: "Alejandra Rios", squad: "Squad 1", role: "Tech Lead", tasks: 11, progress: 72, weekly: "9 cambios", prs: 4, status: "revision" },
  { name: "Raul Molina", squad: "Squad 3", role: "Tech Lead", tasks: 13, progress: 79, weekly: "15 cambios", prs: 6, status: "activo" },
  { name: "Mateo Ceniceros", squad: "Squad 2", role: "Arquitecto", tasks: 9, progress: 63, weekly: "7 cambios", prs: 3, status: "pendiente" },
  { name: "Hector Ibarra", squad: "Squad 4", role: "Engineering Manager", tasks: 10, progress: 91, weekly: "11 cambios", prs: 4, status: "activo" },
  { name: "Nestor Cantu", squad: "Squad 2", role: "ML Engineer", tasks: 8, progress: 45, weekly: "6 cambios", prs: 2, status: "bloqueado" },
] as const;

export const improvements = [
  {
    title: "Normalizar criterios de severidad entre squads",
    impact: "Alto",
    priority: "Alta",
    owner: "PMO + QA Guild",
    recommendation: "Adoptar matriz unica de impacto/probabilidad para riesgos y bugs.",
    effort: "2 semanas",
  },
  {
    title: "Reducir deuda tecnica en integraciones externas",
    impact: "Alto",
    priority: "Alta",
    owner: "Arquitectura",
    recommendation: "Agregar capa anti-corruption para APIs institucionales heredadas.",
    effort: "3 semanas",
  },
  {
    title: "Mejorar throughput de revisiones de PR",
    impact: "Medio",
    priority: "Media",
    owner: "Tech Leads",
    recommendation: "Implementar policy de SLA por tamaño de cambio y reviewer backup.",
    effort: "1 semana",
  },
  {
    title: "Instrumentacion de trazabilidad funcional",
    impact: "Medio",
    priority: "Media",
    owner: "Data Team",
    recommendation: "Completar telemetria de embudo para citas y justificaciones.",
    effort: "2 semanas",
  },
] as const;

export const risks = [
  {
    risk: "Dependencia del webhook institucional para recordatorios",
    severity: "Critico",
    technicalImpact: "Bloquea envio programado en citas",
    operationalImpact: "Aumenta ausentismo y reprogramaciones",
    owner: "Squad 3",
    action: "Habilitar fallback SMTP y cola de reintentos",
    eta: "20 May 2026",
  },
  {
    risk: "Aprobacion juridica pendiente para flujo de evidencias",
    severity: "Medio",
    technicalImpact: "Retiene release de justificaciones",
    operationalImpact: "Continuidad parcial en tramite manual",
    owner: "Squad 1",
    action: "Mesa legal semanal y feature toggle",
    eta: "23 May 2026",
  },
  {
    risk: "Saturacion temporal en analitica semanal",
    severity: "Estable",
    technicalImpact: "Retraso en consolidacion de KPI",
    operationalImpact: "Reporte ejecutivo con latencia",
    owner: "Data Team",
    action: "Escalado horizontal nocturno",
    eta: "19 May 2026",
  },
] as const;

export const chartData = {
  squadProgress: [
    { squad: "S1", progreso: 68 },
    { squad: "S2", progreso: 59 },
    { squad: "S3", progreso: 79 },
    { squad: "S4", progreso: 92 },
  ],
  commitsByWeek: [
    { week: "W1", commits: 62 },
    { week: "W2", commits: 71 },
    { week: "W3", commits: 88 },
    { week: "W4", commits: 97 },
  ],
  tasksDone: [
    { sprint: "S0", completadas: 42 },
    { sprint: "S1", completadas: 58 },
    { sprint: "S2", completadas: 61 },
    { sprint: "S3", completadas: 49 },
  ],
  mvpAdvance: [
    { name: "Core", value: 84 },
    { name: "Operacion", value: 71 },
    { name: "Calidad", value: 66 },
  ],
  moduleDistribution: [
    { name: "Listo", value: 3 },
    { name: "En progreso", value: 4 },
  ],
  productivity: [
    { day: "L", valor: 73 },
    { day: "M", valor: 77 },
    { day: "X", valor: 81 },
    { day: "J", valor: 79 },
    { day: "V", valor: 76 },
  ],
  bugsBySprint: [
    { sprint: "S0", bugs: 3 },
    { sprint: "S1", bugs: 6 },
    { sprint: "S2", bugs: 11 },
    { sprint: "S3", bugs: 15 },
  ],
  healthScore: [
    { name: "Arquitectura", score: 82 },
    { name: "Calidad", score: 74 },
    { name: "Delivery", score: 78 },
    { name: "Riesgos", score: 64 },
  ],
};
